#!/bin/bash

# Script to generate a pdf from markdown.
# Only works on ubuntu based OS

# if you provide the login as a param, it will spit out the correct naming
# otherwise deafults to zn.pdf
LOGIN=$1

# Ensure pandoc for md-latex
if [ $(dpkg -l | grep pandoc | wc -l) -eq 0 ]; then
    echo "`pandoc` package not installed."
    echo "Install using the command apt install pandoc"
    exit 0
fi
echo "pandoc found"

# Ensure texlive for latex-pdf
if [ $(dpkg -l | grep texlive | wc -l) -eq 0 ]; then
    echo "`texlive` package not installed."
    echo "Install using the command apt install texlive"
    exit 0
fi
echo "texlive found"

# use the first param as login
PDF_NAME="zn.pdf"
if [[ -n $LOGIN ]]; then
    PDF_NAME="$LOGIN"_zn.pdf
fi
echo "Generating $PDF_NAME"

# Ignore lines starting with "//", this allows for comments
cat zn.md | grep -v ^\/\/.* | pandoc -s -V geometry:margin=20mm -o "$PDF_NAME"
