name: food_blueprint
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  event_bus: ^2.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.8
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  http: ^1.1.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/BurgerIcon.png"

flutter_native_splash:
  color: "#F4EBDC"
  android_12:
    color: "#F4EBDC"

    # Weird behaviour, icon gets zoomed in, background doesn't get applied
    #icon_background_color: "#F4EBDC"
    #image: assets/icon.png
