name: 'Deploy APK'

on:
  push:
    branches:
      - main
      - pipelines

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: '3.16.5'
          channel: 'stable'
      - run: flutter pub get
      - run: echo ${{ vars.apiKey }} > .env \ echo ${{ vars.baseUrl }} >> .env
      - run: flutter build apk
      - name: Upload apk to artifacts
        uses: actions/upload-artifact@v4.0.0
        with:
          name: 'app-release'
          path: build/app/outputs/flutter-apk/app-release.apk
  
