name: 'Deploy APK'

on:
  push:
    branches:
      - main
      - pipelines

jobs:
  build-apk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          sparse-checkout: app
          working-directory: .
      - name: Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          flutter-version: '3.16.5'
          channel: 'stable'
      - run: cd app/
      - run: flutter pub get
      - run: echo ${{ vars.API_KEY }} > .env \ echo ${{ vars.BASE_URL }} >> .env
      - run: flutter build apk
      - name: Upload apk to artifacts
        uses: actions/upload-artifact@v4.0.0
        with:
          name: 'app-release'
          path: build/app/outputs/flutter-apk/app-release.apk
  
