name: 'Build ZN'

on:
  push:
    branches:
      - main

# The `jobs` key groups together all the jobs that run in the workflow file.
jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install pandoc & texlive
        run: "sudo apt install pandoc texlive"
      - name: Build PDFs
        run: "./create-pdf xotrad00 && ./create-pdf xvandi01 && ./create-pdf xhubin04"
      - name: Upload xotrad00
        uses: actions/upload-artifact@v2
        with:
          name: 'xotrad00.zip'
          path: |
            xotrad00_zn.pdf
            backend/*
            app/*
      - name: Upload xvandi01
        uses: actions/upload-artifact@v2
        with:
          name: 'xvandi01.zip'
          path: |
            xvandi01_zn.pdf
            backend/*
            app/*
      - name: Upload xhubin04
        uses: actions/upload-artifact@v2
        with:
          name: 'xhubin04.zip'
          path: |
            xhubin04_zn.pdf
            backend/*
            app/*
